chore: sync up

diff --git a/foundryup/foundryup b/foundryup/foundryup
--- a/foundryup/foundryup
+++ b/foundryup/foundryup
@@ -1,20 +1,22 @@
 #!/usr/bin/env bash
-set -e
+set -eo pipefail
 
 BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
 FOUNDRY_DIR=${FOUNDRY_DIR:-"$BASE_DIR/.foundry"}
 FOUNDRY_BIN_DIR="$FOUNDRY_DIR/bin"
 FOUNDRY_MAN_DIR="$FOUNDRY_DIR/share/man/man1"
 
+FOUNDRYUP_JOBS=""
+
 BINS=(forge cast anvil chisel)
 
-export RUSTFLAGS="-C target-cpu=native"
+export RUSTFLAGS="${RUSTFLAGS:--C target-cpu=native}"
 
 main() {
   need_cmd git
   need_cmd curl
 
-  while [[ $1 ]]; do
+  while [[ -n $1 ]]; do
     case $1 in
       --)               shift; break;;
 
@@ -24,6 +26,9 @@ main() {
       -p|--path)        shift; FOUNDRYUP_LOCAL_REPO=$1;;
       -P|--pr)          shift; FOUNDRYUP_PR=$1;;
       -C|--commit)      shift; FOUNDRYUP_COMMIT=$1;;
+      -j|--jobs)        shift; FOUNDRYUP_JOBS=$1;;
+      --arch)           shift; FOUNDRYUP_ARCH=$1;;
+      --platform)       shift; FOUNDRYUP_PLATFORM=$1;;
       -h|--help)
         usage
         exit 0
@@ -34,6 +39,12 @@ main() {
         exit 1
     esac; shift
   done
+
+  CARGO_BUILD_ARGS=(--release)
+
+  if [ -n "$FOUNDRYUP_JOBS" ]; then
+    CARGO_BUILD_ARGS+=(--jobs "$FOUNDRYUP_JOBS")
+  fi
 
   # Print the banner after successfully parsing args
   banner
@@ -58,7 +69,7 @@ main() {
     # Enter local repo and build
     say "installing from $FOUNDRYUP_LOCAL_REPO"
     cd "$FOUNDRYUP_LOCAL_REPO"
-    ensure cargo build --bins --release # need 4 speed
+    ensure cargo build --bins "${CARGO_BUILD_ARGS[@]}"
 
     for bin in "${BINS[@]}"; do
       # Remove prior installations if they exist
@@ -79,16 +90,7 @@ main() {
     FOUNDRYUP_TAG=$FOUNDRYUP_VERSION
 
     # Normalize versions (handle channels, versions without v prefix
-    if [[ "$FOUNDRYUP_VERSION" == "nightly" ]]; then
-      # Locate real nightly tag
-      SHA=$(ensure curl -sSf "https://api.github.com/repos/$FOUNDRYUP_REPO/git/refs/tags/nightly" \
-        | grep -Eo '"sha"[^,]*' \
-        | grep -Eo '[^:]*$' \
-        | tr -d '"' \
-        | tr -d ' ' \
-        | cut -d ':' -f2 )
-      FOUNDRYUP_TAG="nightly-${SHA}"
-    elif [[ "$FOUNDRYUP_VERSION" == nightly* ]]; then
+    if [[ "$FOUNDRYUP_VERSION" =~ ^nightly ]]; then
       FOUNDRYUP_VERSION="nightly"
     elif [[ "$FOUNDRYUP_VERSION" == [[:digit:]]* ]]; then
       # Add v prefix
@@ -98,16 +100,15 @@ main() {
 
     say "installing foundry (version ${FOUNDRYUP_VERSION}, tag ${FOUNDRYUP_TAG})"
 
-    PLATFORM="$(uname -s)"
+    uname_s=$(uname -s)
+    PLATFORM=$(tolower "${FOUNDRYUP_PLATFORM:-$uname_s}")
     EXT="tar.gz"
     case $PLATFORM in
-      Linux)
-        PLATFORM="linux"
-        ;;
-      Darwin)
+      linux) ;;
+      darwin|mac*)
         PLATFORM="darwin"
         ;;
-      MINGW*)
+      mingw*|win*)
         EXT="zip"
         PLATFORM="win32"
         ;;
@@ -116,7 +117,8 @@ main() {
         ;;
     esac
 
-    ARCHITECTURE="$(uname -m)"
+    uname_m=$(uname -m)
+    ARCHITECTURE=$(tolower "${FOUNDRYUP_ARCH:-$uname_m}")
     if [ "${ARCHITECTURE}" = "x86_64" ]; then
       # Redirect stderr to /dev/null to avoid printing errors if non Rosetta.
       if [ "$(sysctl -n sysctl.proc_translated 2>/dev/null)" = "1" ]; then
@@ -162,8 +164,8 @@ main() {
       say "installed - $(ensure "$bin_path" --version)"
 
       # Check if the default path of the binary is not in FOUNDRY_BIN_DIR
-      which_path="$(which "$bin")"
-      if [ "$which_path" != "$bin_path" ]; then
+      which_path="$(command -v "$bin" || true)"
+      if [ -n "$which_path" ] && [ "$which_path" != "$bin_path" ]; then
         warn ""
         cat 1>&2 <<EOF
 There are multiple binaries with the name '$bin' present in your 'PATH'.
@@ -204,7 +206,7 @@ EOF
     fi
 
     # Build the repo and install the binaries locally to the .foundry bin directory.
-    ensure cargo build --bins --release
+    ensure cargo build --bins "${CARGO_BUILD_ARGS[@]}"
     for bin in "${BINS[@]}"; do
       for try_path in target/release/$bin target/release/$bin.exe; do
         if [ -f "$try_path" ]; then
@@ -231,17 +233,22 @@ The installer for Foundry.
 
 Update or revert to a specific Foundry version with ease.
 
+By default, the latest nightly version is installed from built binaries.
+
 USAGE:
     foundryup <OPTIONS>
 
 OPTIONS:
     -h, --help      Print help information
-    -v, --version   Install a specific version
-    -b, --branch    Install a specific branch
-    -P, --pr        Install a specific Pull Request
-    -C, --commit    Install a specific commit
-    -r, --repo      Install from a remote GitHub repo (uses default branch if no other options are set)
-    -p, --path      Install a local repository
+    -v, --version   Install a specific version from built binaries
+    -b, --branch    Build and install a specific branch
+    -P, --pr        Build and install a specific Pull Request
+    -C, --commit    Build and install a specific commit
+    -r, --repo      Build and install from a remote GitHub repo (uses default branch if no other options are set)
+    -p, --path      Build and install a local repository
+    -j, --jobs      Number of CPUs to use for building Foundry (default: all CPUs)
+    --arch          Install a specific architecture (supports amd64 and arm64)
+    --platform      Install a specific platform (supports win32, linux, and darwin)
 EOF
 }
 
@@ -258,6 +265,10 @@ err() {
   exit 1
 }
 
+tolower() {
+  echo "$1" | awk '{print tolower($0)}'
+}
+
 need_cmd() {
   if ! check_cmd "$1"; then
     err "need '$1' (command not found)"
@@ -269,15 +280,14 @@ check_cmd() {
 }
 
 # Run a command that should never fail. If the command fails execution
-# will immediately terminate with an error showing the failing
-# command.
+# will immediately terminate with an error showing the failing command.
 ensure() {
   if ! "$@"; then err "command failed: $*"; fi
 }
 
 # Downloads $1 into $2 or stdout
 download() {
-  if [ "$2" ]; then
+  if [ -n "$2" ]; then
     # output into $2
     if check_cmd curl; then
       curl -#o "$2" -L "$1"
@@ -294,21 +304,21 @@ download() {
   fi
 }
 
-# Banner Function for Foundry 
+# Banner Function for Foundry
 banner() {
   printf '
 
 .xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx
- 
+
  ╔═╗ ╔═╗ ╦ ╦ ╔╗╔ ╔╦╗ ╦═╗ ╦ ╦         Portable and modular toolkit
- ╠╣  ║ ║ ║ ║ ║║║  ║║ ╠╦╝ ╚╦╝    for Ethereum Application Development 
+ ╠╣  ║ ║ ║ ║ ║║║  ║║ ╠╦╝ ╚╦╝    for Ethereum Application Development
  ╚   ╚═╝ ╚═╝ ╝╚╝ ═╩╝ ╩╚═  ╩                 written in Rust.
 
 .xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx
 
 Repo       : https://github.com/foundry-rs/
-Book       : https://book.getfoundry.sh/                      
-Chat       : https://t.me/foundry_rs/                         
+Book       : https://book.getfoundry.sh/
+Chat       : https://t.me/foundry_rs/
 Support    : https://t.me/foundry_support/
 Contribute : https://github.com/orgs/foundry-rs/projects/2/
 
@@ -318,4 +328,4 @@ Contribute : https://github.com/orgs/foundry-rs/projects/2/
 }
 
 
-main "$@" || exit 1
+main "$@"
